#include "GLOBAL_CONSTANTS.h"

//GLOBAL_CONSTANTS::GLOBAL_CONSTANTS(unsigned int i_screenWidth, unsigned int i_screenHeight)
//{
//
//}

void GLOBAL_CONSTANTS::SetGlobalConstants(unsigned int i_screenWidth, unsigned int i_screenHeight)
{
	//WINDOW SETTINGS
	GLOBAL_CONSTANTS::SCREEN_WIDTH = i_screenWidth;
	GLOBAL_CONSTANTS::SCREEN_HEIGHT = i_screenHeight;

	//GAME RESOLUTION
	GLOBAL_CONSTANTS::COURT_WIDTH = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_WIDTH * 9.0f / 10.0f);
	GLOBAL_CONSTANTS::COURT_HEIGHT = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_HEIGHT * 9.0f / 10.0f);
	GLOBAL_CONSTANTS::HOR_MARGIN = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_WIDTH / 20.0f);         //horizontal margin
	GLOBAL_CONSTANTS::VERT_MARGIN = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_HEIGHT / 20.0f);       //vertical margin

	//MENU RESOLUTION
	GLOBAL_CONSTANTS::BUTTON_WIDTH = GLOBAL_CONSTANTS::SCREEN_WIDTH / 3;
	GLOBAL_CONSTANTS::BUTTON_HEIGHT = GLOBAL_CONSTANTS::SCREEN_HEIGHT / 10;
}

GLOBAL_CONSTANTS::GLOBAL_CONSTANTS()
{
}

//WINDOW SETTINGS
unsigned int GLOBAL_CONSTANTS::SCREEN_WIDTH = 0;
unsigned int GLOBAL_CONSTANTS::SCREEN_HEIGHT = 0;

//GAME RESOLUTION
float GLOBAL_CONSTANTS::COURT_WIDTH = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_WIDTH * 9.0f / 10.0f);
float GLOBAL_CONSTANTS::COURT_HEIGHT = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_HEIGHT * 9.0f / 10.0f);
float GLOBAL_CONSTANTS::HOR_MARGIN = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_WIDTH / 20.0f);         //horizontal margin
float GLOBAL_CONSTANTS::VERT_MARGIN = static_cast<float>(GLOBAL_CONSTANTS::SCREEN_HEIGHT / 20.0f);       //vertical margin

//MENU RESOLUTION
float GLOBAL_CONSTANTS::BUTTON_WIDTH = GLOBAL_CONSTANTS::SCREEN_WIDTH / 3;
float GLOBAL_CONSTANTS::BUTTON_HEIGHT = GLOBAL_CONSTANTS::SCREEN_HEIGHT / 10;


GLOBAL_CONSTANTS::~GLOBAL_CONSTANTS()
{
}
